### ISSUE TITLE
Add COC to repo

### ISSUE THREAD

**Issue by chuckharmston** [Denver-Devs/denverdevs.org#11]
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by danhannigan** [comment]
Great idea. I feel like this one is nice and succinct: https://www.contributor-covenant.org/version/1/4/code-of-conduct

**Comment by danhannigan** [comment]
Added one today!

**Comment by chuckharmston** [comment]
:dan_heart_eyes:
