### ISSUE TITLE
Broken link in contributing.md

### ISSUE THREAD

**Issue by galbwe** [Denver-Devs/denverdevs.org#125]
The link to denverdevs.org from contributing.md leads to a 404 page.

http://denverdevs.org/resources/contributing/

Not sure if this is on a different page now or if the link should be deleted.

**Comment by danhannigan** [comment]
Ah yeah, that's a relic from the past that hasn't been updated. I removed the text, I'll pop up a new ticket for building out the contributing page again. Thanks for catching that!
