### ISSUE TITLE
Job Filters to Narrow Search 

### ISSUE THREAD

**Issue by ChaseDudas** [Denver-Devs/denverdevs.org#131]
**Feature(s) being requested**
- [ ] Figure out how to make the filters look better (maybe a horizontal filter bar up top?)
- [ ] Allow filtering by Location

**Describe the solution you'd like**
I think the proposed filter section in the following mockups would work exceptionally well. 

![image](https://user-images.githubusercontent.com/60021702/171302370-0b2f1e91-531c-41c7-af62-0d891940514e.png)

![Kapture_2022-05-15_at_18 36 40](https://user-images.githubusercontent.com/60021702/171302461-a5b0718e-bc62-4384-bc08-3dec2449d10a.gif)

**Describe alternatives you've considered**
I have not viewed any other options yet.

**Additional context**
The additional context was provided above.

**Comment by danhannigan** [comment]
Gah! I don't get github notifications for these things for some weird reason, but yeah, building this out this way is on my radar. If you're feeling ambitious you're welcome to go take a crack at it, too. (there are additional changes with that page, regarding grid layout and more - but for the sake of scope focusing in on the changes for the filters seems like a good start) 

Here's thew working figma with the specific updates: https://www.figma.com/file/PDPRpS5FGByW7M1wInI8kB/New-Features?node-id=0%3A1

**Comment by ChaseDudas** [comment]
No worries! I think I would have to tag you, like @danhannigan, to send the alert to you. 

Thank you for including the Figma files!

**Comment by danhannigan** [comment]
@ChaseDudas Ah yep that tag did it! Feel free to tag me on things in the future since I'm the main one maintaining or paying attention
