### ISSUE TITLE
Get our metadata / SEO on track 

### ISSUE THREAD

**Issue by danhannigan** [Denver-Devs/denverdevs.org#141]
I slapped the site together to get it working and didn't do my due diligence to get the metadata + SEO in a good spot.

Maybe we could use something like Next SEO: https://www.npmjs.com/package/next-seo to get it all bundled up. 

Open to any suggestions or ideas.

**Comment by danhannigan** [comment]
Shout out to @tdronkers04 for getting this cleared up!

**Comment by tdronkers04** [comment]
> Shout out to @tdronkers04 for getting this cleared up!

My pleasure Dan thanks for the opportunity!
