### ISSUE TITLE
Design a 404 page

### ISSUE THREAD

**Issue by danhannigan** [Denver-Devs/denverdevs.org#144]
We don't have one! Let's make one - opening this issue up for the **design** aspect of it.

**Comment by ShishuSidharth** [comment]
can you please guide me that if you want a webpage showing 404 not found designed in html and css?

**Comment by anushas-dev** [comment]
@Nandinisaagar and @ShishuSidharth, I would like help out as well.
Meanwhile for starters, this project is built on 
[Next.js](http://nextjs.org/)
[Chakra UI](https://chakra-ui.com/)
[Supabase](http://supabase.com/)
[Netlify](http://netlify.com/) - Hosting and CI.
The setup is in the readme, so follow along.

If @danhannigan is okay with 3 of us giving this a try, we can collectively design, code, make custom 404/_error.js pages.
