### ISSUE TITLE
React Hydration Error

### ISSUE THREAD

**Issue by tdronkers04** [Denver-Devs/denverdevs.org#149]
**Describe the bug**
Upon starting the Next app locally, I'm seeing the following runtime error:

`Error: Hydration failed because the initial UI does not match what was rendered on the server.`

**To Reproduce**
1. cloned repo locally
2. installed dependencies with yarn
3.  started development server with `yarn dev`

**Expected behavior**
The application should not produce a runtime error

**Screenshots**
![Screen Shot 2022-10-03 at 1 22 46 PM](https://user-images.githubusercontent.com/72320460/193661086-4f890323-6395-444d-bdeb-9e8730d0ac4b.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Browser: Firefox Developer Edition 
 - Version: 106.0b7

**Comment by danhannigan** [comment]
It's definitely in the Header somewhere

**Comment by danhannigan** [comment]
Okay, so on further digging - it's React 18 + Next, and we've got some ugly HTML structure in that header - before it would come through as a silent warning, and now it's a full on angry takeover in Next

**Comment by danhannigan** [comment]
Looks like we had some funky double a tag nesting inside of the header, which react 18 + next 12 do not like at all. This should clear it up, but I noticed there's also another bug inside the job card that produces similar results, so I'll go fix that.
