### ISSUE TITLE
Re-write Recruiter / Gig formatting page. 

### ISSUE THREAD

**Issue by danhannigan** [Denver-Devs/denverdevs.org#32]
As we've grown different issues have popped up around recruiters / gigs / and staffing agencies. 

We need to re-write the rules to make it clear what kind of behavior we require from these various groups w/o harming their business. A rough outline follows but could use some modifications & proofreading. 

_EDIT:_ Condensing work into a branch that can be pulled down and reviewed: https://github.com/Denver-Devs/denverdevs.org/commit/a102430dbbaef7954d66fd2b820cfe528ad9af37

**Comment by abelgoodwin1988** [comment]
>     * Do not post walls of text that drown out other posts. Keep it tidy and concise.
I think these posts should also be deleted with a link to these guidelines. It may also be helpful to have the guidelines in a non-bullet format so we can reference the exact point for why it was deleted to help them create more meaningful posts.

The formatting guidelines specify that they say what the stack is twice, that's cool if we want to really make sure they do that.

Looking good.

**Comment by danhannigan** [comment]
Good call on that @abelgoodwin1988

**Comment by abelgoodwin1988** [comment]
Also now looking at the gig formatting page, would it be a good idea for us to include a good 'sample' posting of each in addition the formatting?

**Comment by Robbie-Smith** [comment]
I'd prefer if it was required that a recruiter have a real image.

**Comment by danhannigan** [comment]
I've re-written the proposal as an actual formatted page you can check out here: https://github.com/Denver-Devs/denverdevs.org/tree/update/recruiter-guidelines

**Comment by kylecoberly** [comment]
I don't have any problems with making recruiters jump through any hoops that don't essentially negate the business model. Required photos, starting every post with "I AM A RECRUITER", etc. seems perfectly fine to me. I also don't think anything is particularly broken. We're not flooded with posts of any kind, and one dev's shitty agency recruiter posting is another's great opportunity.

**Comment by danhannigan** [comment]
Completed by https://github.com/Denver-Devs/denverdevs.org/commit/1eb62c6ed1cbace0dbd34cdb53231d347b37d054
