### ISSUE TITLE
Write out more robust and informative rules. 

### ISSUE THREAD

**Issue by danhannigan** [Denver-Devs/denverdevs.org#34]
As we've grown our rules have needed to adapt -- new edge cases, new behavior that could use a bit of friendly nudging, etc. We should write out some new rules around this, formatting them in a way similar to the new Recruiter guidelines (where each rule is also a linkable header that we can cite)

**Comment by dannyfritz** [comment]
I generally like code of conducts better than detailed rules. Requires moderators to be watching for CoC to work though.

**Comment by danhannigan** [comment]
We have both to handle either scenario and preference: The rules being a bit more scannable and more appropriate to our community specifically, while the CoC is a bit of a blanket policy that covers a lot of other concerns and issues.

**Comment by dannyfritz** [comment]
Here is the Rust community's for an example:
https://www.rust-lang.org/policies/code-of-conduct
<img width="1315" alt="screen shot 2019-03-07 at 4 28 18 pm" src="https://user-images.githubusercontent.com/315788/53996550-0dd97b80-40f6-11e9-9542-e643ffc2fd08.png">

**Comment by danhannigan** [comment]
We do have our own if you're not familiar!
Code of Conduct:  https://denverdevs.org/resources/code-of-conduct/
Rules: https://denverdevs.org/resources/rules/

**Comment by abelgoodwin1988** [comment]
Hmmm,

> As we've grown our rules have needed to adapt -- new edge cases, new behavior that could use a bit of friendly nudging, etc. 

For context, what has happened that isn't covered in the rules / CoC? I feel like they're broad enough to cover most ass-hattery, even mine.

**Comment by danhannigan** [comment]
They’re fairly encompassing but also dangerously vague in some ways - to where it’s not clear to users what is/isn’t okay. A few examples are: 

Unwanted messages (spam, solicitation, etc) and what that encompasses / looks like & our process for responding to that. 

Personal advertisements and the right time / place for that. 

Identitfing information (personal info etc) 

Also clarifying our policies for how we handle things so folks know what to expect. 

We handle a lot of stuff behind the scenes and fairly quietly so I can see how context for helping here feels probably not adequate. This is also for new formatting / updating and also for the sake of transparency: So folks know that updates will be coming, can see progress, and chime in if they feel the need.
