### ISSUE TITLE
Conference Link URLs seem to be in reverse order from the visual UI element.

### ISSUE THREAD

**Issue by jonzfisher** [Denver-Devs/denverdevs.org#44]
**Describe the bug**

This might be just me, but the URLs linked on each conference on DenverDevs.org/events seem to be sorted reversed on the live site, but when I cloned it down, my local seems to have the URLs ordered correctly.

**To Reproduce**
1. Go to https://denverdevs.org/events/#conferences in Chrome or Safari i.e. not in Firefox.
2. Hover over the link to see which URL it's going to.
3. The first link will link to the last of the list and the last to the first, and the rest are reversed as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/6652546/59309950-c8c76700-8c59-11e9-9073-6b9145b10b09.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Majave
 - Browser [e.g. chrome, safari] Chrome and Safari but for some reason not in Firefox
 - Version [e.g. 22] E.g. Chrome Version 74.0.3729.169

**Comment by danhannigan** [comment]
Good catch @jonzfisher, it's definitely doing that. I thought we had fixed this before but the bug is back.

**Comment by jonzfisher** [comment]
Definitely tried looking into it, but when I saw dev didn't also reflect the issue, I realized it might go deeper than I thought. This might be a good time to say thanks for making the events page! Definitely my favorite resource to see what's going on. Huge win!
